### ISSUE TITLE
Change names of interfaces

### ISSUE THREAD

**Issue by FreePhoenix888** [deep-foundation/capacitor-camera#7]
https://github.com/deep-foundation/capacitor-camera/blob/78b80d6551583f8cc24ad43710465857bdffcc20/src/upload-gallery.ts#L6

I think we would better explicitly declare that interface is used as ...Param
IUploadGallery -> UploadGalleryParam (or IUploadGalleryParam)

@Konard , what do you think about it?

**Comment by konard** [comment]
@FreePhoenix888 you can also call it Options. Anyway yes, I agree with the need to state it explicitly.
